version: '3.7'

services:
  # Database

  web:
    restart: always
    build:
      context: "."
      dockerfile: "Dockerfile"    
    image: zamy_web_app:3.0
    links:
      - db
    volumes: 
     - ".:/code"
     - ".:/var/www/html/zamy"
    ports:
     - "8500:80"
    stdin_open: true
    tty: true
    depends_on:
      - db

  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: zamy_ci
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root 

volumes:
  db_data:
  web_data:

